"""empty message

Revision ID: 5306e7c9c738
Revises: 
Create Date: 2022-04-18 12:05:09.891370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5306e7c9c738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('companyname', sa.String(), nullable=True),
    sa.Column('jobtitle', sa.String(), nullable=True),
    sa.Column('adverttitle', sa.String(), nullable=True),
    sa.Column('advertdescription', sa.String(), nullable=True),
    sa.Column('advertphoto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisements')
    # ### end Alembic commands ###
